In [1]:
pwd

'C:\\Users\\Admin'

In [2]:
##NumPy Exercises

In [4]:
import numpy as np

Create an Array of 10 zeros

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an Array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an Array of 10 fives

In [9]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
arr1d=np.arange(0,9)

In [22]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
arr2d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [26]:
np.random.rand()

0.5186762012335179

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
np.random.randn(25)

array([ 0.8245543 , -0.18093342, -0.15814696,  0.27256789,  0.59321884,
        0.35414905, -0.112057  ,  0.54361888,  1.45831606, -0.74876748,
       -1.50864979,  0.14275005, -0.88609612, -0.55446125, -0.37678081,
       -0.2647167 ,  0.33598617, -0.79523014, -0.71086337, -0.51467642,
       -0.76285717, -1.93879487, -0.38256174,  0.13418033,  0.54406104])

Create the following matrix:

In [38]:
a=np.arange(0,1,0.01)## not able to Create

In [37]:
a

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [42]:
a.reshape(10,10)## not able to create Matrix as required

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

Create an array of 20 linearly spaced points between 0 and 1:

In [45]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy Indexing and Selection

In [46]:
arr=np.arange(1,26).reshape(5,5)

In [47]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [50]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [54]:
arr[3,4]

20

In [55]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
##output req 2,7,12

In [57]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [58]:
##output req as 21,22,23,24,25

In [59]:
arr[4:5]

array([[21, 22, 23, 24, 25]])

In [60]:
arr[4:5,0:6]

array([[21, 22, 23, 24, 25]])

In [61]:
arr[4,]

array([21, 22, 23, 24, 25])

In [62]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
##output req last two rows

In [68]:
arr[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
##ouput req Get the sum of all the values in mat

In [69]:
arr.sum()

325

Get the standard deviation of the values in mat

In [72]:
np.random.randn(26)## not able to get answer

array([-1.10084798, -2.15080573, -1.02397259,  0.90985197,  0.56658089,
        1.07067613,  0.7037254 , -0.88909057,  0.02884826,  2.67523841,
        1.15726533, -1.78953222,  0.41662767,  0.81286998, -0.73136966,
       -0.82987283,  0.25757509,  0.37461826, -0.39488465,  0.16457066,
        0.26026836,  0.03586069, -0.68967612,  0.03260348, -0.92334651,
       -0.04349578])

Get the sum of all the columns in mat

In [73]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
arr.sum(axis=1) ## for Column

array([ 15,  40,  65,  90, 115])

In [75]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [77]:
arr.sum(axis=0)## for Column

array([55, 60, 65, 70, 75])